const http = require('http');

const user = process.env.APP_USERNAME || 'unknown-user';

http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain' });

  res.write(
    '===== NODE.JS APPLICATION OUTPUT =====\n\n'
  );
  res.write(
    'Source        : Node.js Backend\n'
  );
  res.write(
    'Access Path   : This response is generated by the APP\n'
  );
  res.write(
    `User (Vault)  : ${user}\n`
  );
  res.write(
    'Status        : Application is running successfully\n'
  );
  res.write(
    '=====================================\n'
  );

  res.end();
}).listen(3000);
